### ISSUE TITLE
Harvest and Google auth?

### ISSUE THREAD

**Issue by xendk** [kostajh/harvest.el#13]
I might just be stupid, but I've not managed to get it working on my account where I usually sign in using Google.

I tried setting my password on https://id.getharvest.com/profile, but it's not entirely clear whether my email address is then the username, and it certainly doesn't work.

Anyone have it working with a usually Google authed account?

**Comment by xendk** [comment]
Nevermind, it _was_ me being stupid.

**Comment by kostajh** [comment]
Glad you were able to figure it out! If there are improvements that can be made to the docs, a PR would be very welcome.

**Comment by xendk** [comment]
Not much that can be done in a PR to make people actually read and understand the hostname prompt. ;-)
